config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root "home#index"
  get "/contract" => "pages#contract"
  resource :profile
  resource :feed, only: [:show]

  namespace :admin do
    resources :posts
  end
end

app/models/account.rb
class Account < ApplicationRecord
  rolify
  belongs_to :user
  has_many :posts

  after_create :assign_role

  def assign_role
    self.add_role(:member) if self.roles.blank?
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  validates :street, :city, :postal_code, :country, presence: true, length: { maximum: 200 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name, presence: true, length: { maximum: 200 }
  validates :phone_number, presence: true, length: { maximum: 20 }

  has_one :address, as: :addressable

  accepts_nested_attributes_for :address
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :accounts, :join_table => :accounts_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :destroy
  has_one :address, through: :profile
  has_one :account, dependent: :destroy

  after_create :create_account

  private

  def create_account
    self.create_account!
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AuthenticatedController
  def index
    @pagy, @posts = pagy(Post.all.order(created_at: :desc))
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.account.posts.create(
      post_creation_params
    )
    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_url, notice: "Post succuessfully created" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_update_params)
    respond_to do |format|
      if @post.errors.present?
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to admin_post_url(@post), notice: "Post succuessfully edited" }
        format.json { render :show, status: :ok, location: @post }
      end
    end    
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_path, notice: "Post deleted successfully" }
    end
  end

  private

  def post_creation_params
    params.require(:post).permit(
      :title,
      :description,
    )
  end

  def post_update_params
    params.require(:post).permit(
      :id,
      :title,
      :description,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
  layout :application_authenticated
  before_action :set_profile

  def set_profile
    @profile = current_user.profile
  end

  def application_authenticated
    "application_authenticated"
  end
end

app/controllers/devise_turbo_controller.rb
class DeviseTurboController < ApplicationController
  # class Responder < ActionController::Responder
  #   def to_turbo_stream
  #     controller.render(options.merge(formats: :html))
  #   rescue ActionView::MissingTemplate => error
  #     if get?
  #       raise error
  #     elsif has_errors? && default_action
  #       render rendering_options.merge(formats: :html, status: :unprocessable_entity)
  #     else
  #       redirect_to navigation_location
  #     end
  #   end
  # end

  class Responder < ActionController::Responder
    def to_turbo_stream
      if @default_response
        @default_response.call(options.merge(formats: :html))
      else
        controller.render(options.merge(formats: :html))
      end
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        navigation_behavior error
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/feeds_controller.rb
class FeedsController < AuthenticatedController
  def show
    @posts = []
  end
end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  def index

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contract
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "contract"   # Excluding ".pdf" extension.
      end
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AuthenticatedController
  def show
    if current_user.profile.nil?
      redirect_to new_profile_path
    else
      @profile = current_user.profile
    end
  end

  def new
    if current_user.profile.present?
      redirect_to profile_url(current_user.profile)
    else
      @profile = Profile.new
      @profile.build_address
    end
  end

  def create
    return if current_user.profile.present?

    @profile = current_user.create_profile(profile_creation_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url, notice: "Profile succuessfully created" }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update(profile_update_params)
    respond_to do |format|
      if @profile.errors.present?
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to profile_url, notice: "Profile succuessfully edited" }
        format.json { render :show, status: :ok, location: @profile }
      end
    end
  end

  private

  def profile_creation_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :phone_number,
      address_attributes: [
        :street,
        :city,
        :country,
        :postal_code,
      ]
    )
  end

  def profile_update_params
    params.require(:profile).permit(
      :id,
      :first_name,
      :last_name,
      :phone_number,
      address_attributes: [
        :street,
        :city,
        :country,
        :postal_code,
        :id,
      ]
    )
  end
end

app/helpers/alerts_helper.rb
# frozen_string_literal: true

module AlertsHelper
  def alert_class(flash_type)
    case flash_type
    when 'alert' then 'alert-danger'
    when 'notice' then 'alert-success'
    else
      raise "Invalid flash_type: #{flash_type.inspect}"
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def app_name
    "Eclectic Experience"
  end

  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def border_error(error)
    error ? " border-red-500" : " border-gray-200"
  end
end

app/views/admin/posts/edit.html.erb
<div class="w-full max-w-2xl mx-auto">
  <div class="flex justify-end">
    <%= link_to admin_post_path, data: { turbo_method: :delete, confirm: 'Are you sure?' } do %>
      <svg class="h-6 w-6"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
      <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="4" y1="7" x2="20" y2="7" />  <line x1="10" y1="11" x2="10" y2="17" />  <line x1="14" y1="11" x2="14" y2="17" />
        <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />  <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
      </svg>
    <% end %>
  </div>
  <%= form_for @post, url: admin_post_path(@post), method: :put, html: { class: "" } do |form| %>
    <div class="-mx-3 mb-6">
      <div class="w-full px-3 mb-6 md:mb-0">
        <%= form.label :title, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field(
              :title,
              class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.errors.messages[:first_name].present?)}",
                    
              placeholder: "Whats happening!")
        %>
        <% if @post.errors.messages[:title].present? %>
          <p class="text-red-500 text-xs italic">Please fill out this field.</p>
        <% end %>
      </div>
      <div class="w-full px-3 mb-6 md:mb-0">
        <%= form.label :description, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_area(
            :description,
            class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.errors.messages[:last_name].present?)}",
            rows: 10,
            placeholder: "Hey folks ...") %>
        <% if @post.errors.messages[:description].present? %>
          <p class="text-red-500 text-xs italic">Please fill out this field.</p>
        <% end %>
      </div>
    </div>
    <div>
      <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class="flex flex-wrap">
  <%= render "shared/posts", posts: @posts, pagy: @pagy, editable: true %>
  <div class="w-1/3">
    <%= link_to new_admin_post_path, class: "flex items-center px-4 py-2 mt-2" do %>
      <svg class="h-12 w-12 mr-2 text-gray-800 hover:bg-gray-200"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
      </svg>      
    <% end %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto max-w-md md:max-w-2xl mb-8">
<div class="px-4 py-6 md:mx-auto md:max-w-2xl min-w-full">
  <div class="flex border-b py-4 px-4">
      <h2 class="text-lg font-semibold text-gray-900 -mt-1 w-1/2 text-start"><%= @post.title %></h2>
      <div class="flex text-sm text-gray-700 w-1/2 text-end justify-end">
        <small class="mr-2"><%= distance_of_time_in_words(Time.current, @post.created_at) %></small>
        <%= link_to edit_admin_post_path(@post) do %>
          <svg class="h-4 w-4"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
          </svg>
        <% end %>
      </div>
  </div>
  <p class="mt-3 text-gray-700 text-sm text-start py-4 px-4">
    <%= @post.description %>
  </p>
 </div>
</div>

app/views/feeds/show.html.erb
<%= render "shared/posts", posts: @posts, pagy: @pagy, editable: false %>

app/views/home/index.html.erb
<main class='mx-auto max-w-lg my-10 px-4'>

</main>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: profile_path, method: method, html: { class: "w-full max-w-2xl mx-auto" } do |form| %>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <%= form.label :first_name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field(
            :first_name,
            class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.errors.messages[:first_name].present?)}",
                  
            placeholder: "Jane")
      %>
      <% if @profile.errors.messages[:first_name].present? %>
        <p class="text-red-500 text-xs italic">Please fill out this field.</p>
      <% end %>
    </div>
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <%= form.label :last_name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field(
          :last_name,
          class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.errors.messages[:last_name].present?)}",
          placeholder: "Doe") %>
      <% if @profile.errors.messages[:last_name].present? %>
        <p class="text-red-500 text-xs italic">Please fill out this field.</p>
      <% end %>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full px-3">
      <%= form.label :phone_number, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field :phone_number, class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.errors.messages[:phone_number].present?)}", placeholder: "+491765670000" %>
      <% if @profile.errors.messages[:phone_number].present? %>
        <p class="text-red-500 text-xs italic">Please fill out this field.</p>
      <% end %>          
    </div>      
  </div>
  <%= form.fields_for :address do |address_form| %>
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= address_form.label :street, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= address_form.text_field :street, class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.address.errors.messages[:street].present?)}", placeholder: "Berliner Str. 18" %>
      </div>
      <% if @profile.address.errors.messages[:street].present? %>
        <p class="text-red-500 text-xs italic">Please fill out this field.</p>
      <% end %>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
        <%= address_form.label :city, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= address_form.text_field :city, class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.address.errors.messages[:city].present?)}", placeholder: "Berlin" %>
        <% if @profile.address.errors.messages[:city].present? %>
          <p class="text-red-500 text-xs italic">Please fill out this field.</p>
        <% end %>
      </div>
      <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
        <%= address_form.label :postal_code, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= address_form.text_field :postal_code, class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.address.errors.messages[:postal_code].present?)}", placeholder: "10786" %>
        <% if @profile.address.errors.messages[:postal_code].present? %>
          <p class="text-red-500 text-xs italic">Please fill out this field.</p>
        <% end %>
      </div>
      <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
        <%= address_form.label :country, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= address_form.text_field :country, class: "appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" + "#{border_error(@profile.address.errors.messages[:country].present?)}", placeholder: "Germany" %>
        <% if @profile.address.errors.messages[:country].present? %>
          <p class="text-red-500 text-xs italic">Please fill out this field.</p>
        <% end %>
      </div>
    </div>
  <% end %>
  <div>
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="p-6 border-b">
  <div class="font-bold text-xl text-green-900 p-4">Profile</div>
</div>

<div class="px-6 pt-4 pb-2">
  <div class="border-b flex p-4">
    <div class="w-1/3">Name</div>
    <div class="w-2/3"><%= @profile.first_name + " " + @profile.last_name %></div>
  </div>
  <div class="border-b flex p-4">
    <div class="w-1/3">Email</div>
    <div class="w-2/3"><%= @profile.user.email %></div>
  </div>
  <div class="border-b flex p-4">
    <div class="w-1/3">Phone Number</div>
    <div class="w-2/3"><%= @profile.phone_number %></div>
  </div>
  <div class="border-b flex p-4">
    <div class="w-1/3">Street</div>
    <div class="w-2/3"><%= @profile.address.street %></div>
  </div>
  <div class="border-b flex p-4">
    <div class="w-1/3">City</div>
    <div class="w-2/3"><%= @profile.address.city %></div>
  </div>
  <div class="border-b flex p-4">
    <div class="w-1/3">Postal Code</div>
    <div class="w-2/3"><%= @profile.address.postal_code %></div>
  </div>
  <div class="flex p-4 mb-4">
    <div class="w-1/3">Country</div>
    <div class="w-2/3"><%= @profile.address.country %></div>
  </div>
  <div class="flex p-4 mb-4">
    <%= link_to "Edit", edit_profile_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</div>

app/views/shared/_navbar_authenticated.html.erb
<header>
  <nav class="">
    <div class="flex h-16 bg-white border-b border-gray-200 justify-end">
      <div class="">
        <%= link_to profile_path, class: "flex px-4 py-2 mt-3 text-gray-800" do %>
          <svg class="h-6 w-6"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z"/><circle cx="12" cy="7" r="4" />  <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
          </svg>
        <% end %>
      </div>
      <div class="">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex px-4 py-2 mt-3 text-gray-800" do %>
          <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
          </svg>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<div class="hidden md:flex flex-col w-64 bg-white shadow-2xl rounded-2xl m-2 relative bg-neutral" data-controller="sidebar">
    <div class="mt-10 flex-grow">
        <nav class="flex-1 mt-6">
            <%= link_to feed_path, class: "flex items-center mt-12 px-2 hover:border-l-2 hover:border-zinc-400 border-l-2 border-white" do %>
                <div class="flex hover:bg-gray-100 w-full h-full p-2 rounded-lg">
                    <svg class="h-6 w-6 mr-2"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 0 1-2.25 2.25M16.5 7.5V18a2.25 2.25 0 0 0 2.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 0 0 2.25 2.25h13.5M6 7.5h3v3H6v-3Z"></path>
                    </svg>
                    <span class="text-nuetral-600 font-medium">Feed</span>
                </div>
            <% end %>
        </nav>
    </div>
    <div data-sidebar-target="profileButton" class="absolute bottom-10 left-20 hidden">
        <!-- #-- <button class="w-4 absolute top-9 right-3" data-action="click->hello#closePopUp">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
        </button> -->
        <ul 
            class="rounded-2xl my-6 shadow-lg py-8 w-64 bg-white border border-gray-200 z-10"
        >
            <li class="hover:border-l-2 hover:border-zinc-400 border-l-2 border-white">
                <a class="flex items-center mx-2 hover:bg-gray-100 h-full rounded-lg" href="#">
                    <div class="flex hover:bg-gray-100 w-full h-full p-2 rounded-lg">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-6 w-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                        </svg>
                    <span class="">Account Settings</span>
                    </div>
                </a>
            </li>
            <li class="hover:border-l-2 hover:border-zinc-400 border-l-2 border-white">
                <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex items-center mx-2 hover:bg-gray-100 h-full rounded-lg" do %>
                    <div class="flex hover:bg-gray-100 w-full h-full p-2 rounded-lg">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-6 w-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
                        </svg>
                        <span class="">Logout</span>
                    </div>
                <% end %>
            </li>
        </ul>
    </div>
    <button data-action="sidebar#toggle" class="mx-auto w-48 mb-4 px-4 py-2 text-neutral-100 font-medium rounded-full shadow bg-gradient-to-r from-red-400 to-pink-400 hover:from-red-500 hover:to-pink-500">
        <%= current_user.email %>
    </button>
</div>
<div class="md:hidden w-full mt-4">
    <nav class="flex items-center justify-between flex-wrap p-6 rounded-lg shadow-xl border mx-2 bg-white" data-controller="sidebar">
        <div class="flex items-center flex-shrink-0 text-neutral-600 mr-6">
            <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
            <span class="font-semibold text-xl tracking-tight">My Project</span>
        </div>
        <div class="block" data-action="click->sidebar#toggle">
            <button class="flex items-center px-3 py-2 border rounded hover:border-gray-400">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
            </button>
        </div>
        <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto" data-sidebar-target="profileButton">
            <div class="text-sm md:flex-grow">
                <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 mr-4">
                    Docs
                </a>
                <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 mr-4">
                    Examples
                </a>
                <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0">
                    Blog
                </a>
                <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "block mt-4 lg:inline-block lg:mt-0" do %>
                    <span class="">Logout</span>
                <% end %>
            </div>
        </div>
    </nav>
</div>